//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class audit_log
    {
        public audit_log()
        {
            this.audit_log_clause = new HashSet<audit_log_clause>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_audit { get; set; }
        public Nullable<byte> grade { get; set; }
        public Nullable<byte> status { get; set; }
        public string finding { get; set; }
        public string requester { get; set; }
        public Nullable<int> id_pir { get; set; }
        public string process { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string reference { get; set; }
    
        public virtual ICollection<audit_log_clause> audit_log_clause { get; set; }
        public virtual pir pir { get; set; }
    }
    
}
