//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class component
    {
        public component()
        {
            this.sub_component = new HashSet<sub_component>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_equipment_part { get; set; }
        public string tag_number { get; set; }
        public string description { get; set; }
    
        public virtual equipment_part equipment_part { get; set; }
        public virtual ICollection<sub_component> sub_component { get; set; }
    }
    
}
