//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class discipline
    {
        public discipline()
        {
            this.equipments = new HashSet<equipment>();
        }

        public int id { get; set; }
        public string title { get; set; }

        public virtual ICollection<equipment> equipments { get; set; }
    }
    
}
