//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class equipment_part
    {
        public equipment_part()
        {
            this.components = new HashSet<component>();
            this.part_unit_event = new HashSet<part_unit_event>();
        }
    
        public int id { get; set; }
        public int id_equipment { get; set; }
        public int id_parts { get; set; }
        public Nullable<double> mtbf { get; set; }
        public Nullable<double> mttr { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<double> lead_time { get; set; }
        public Nullable<System.DateTime> installed_date { get; set; }
        public Nullable<System.DateTime> obsolete_date { get; set; }
    
        public virtual ICollection<component> components { get; set; }
        public virtual equipment equipment { get; set; }
        public virtual part part { get; set; }
        public virtual ICollection<part_unit_event> part_unit_event { get; set; }
    }
    
}
