//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class equipment_daily_report_table
    {
        public int id { get; set; }
        public Nullable<int> id_equipment_daily_report { get; set; }
        public Nullable<int> id_equipment { get; set; }
        public string min_limit { get; set; }
        public string max_limit { get; set; }
        public string unit { get; set; }
        public string tag_value { get; set; }
        public string time { get; set; }
        public string name_operator { get; set; }
        public string keterangan { get; set; }
        public string barcode { get; set; }
    
        public virtual equipment_daily_report equipment_daily_report { get; set; }
        public virtual equipment equipment { get; set; }
    }
    
}
