//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class equipment_daily_report
    {
        public equipment_daily_report()
        {
            this.equipment_daily_report_table = new HashSet<equipment_daily_report_table>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<equipment_daily_report_table> equipment_daily_report_table { get; set; }
    }
    
}
