//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class foc_target_paf
    {
        public int id { get; set; }
        public int id_foc { get; set; }
        public Nullable<int> tahun { get; set; }
        public Nullable<int> bulan { get; set; }
        public Nullable<double> target_paf { get; set; }
    
        public virtual foc foc { get; set; }
    }
    
}
