//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class foc_op_avail
    {
        public int id { get; set; }
        public int id_foc { get; set; }
        public Nullable<double> op_avail { get; set; }
        public Nullable<System.DateTime> plant_down { get; set; }
        public Nullable<System.DateTime> plant_up { get; set; }
        public Nullable<int> selisih { get; set; }
        public Nullable<int> selisih_paf { get; set; }
        public Nullable<double> pof_bulanan { get; set; }
        public Nullable<double> paf_bulanan { get; set; }
        public Nullable<double> paf { get; set; }
        public Nullable<int> bulan { get; set; }
        public Nullable<int> tahun { get; set; }
        public string tipe { get; set; }
    
        public virtual foc foc { get; set; }
    }
    
}
