//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class incident_report_log
    {
        public int id { get; set; }
        public Nullable<int> id_ir { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string username { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
    }
    
}
