//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class ma
    {
        public int id { get; set; }
        public int id_foc { get; set; }
        public double tadd { get; set; }
        public double tadt_hours { get; set; }
        public double ta_interval { get; set; }
        public double ntamdd { get; set; }
        public double study_year_ntamd { get; set; }
        public double prior_year_ntamd { get; set; }
        public double ntamsd { get; set; }
        public double study_year_ms { get; set; }
        public double prior_year_ms { get; set; }
        public double days_in_study_year { get; set; }
        public System.DateTime last_update { get; set; }
        public Nullable<double> masd { get; set; }
        public Nullable<double> ma1 { get; set; }
        public Nullable<byte> category { get; set; }
        public Nullable<byte> type { get; set; }

        public virtual foc foc { get; set; }
    }
    
}
