//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class she_illness_report
    {
        public int id { get; set; }
        public Nullable<byte> chest_injury { get; set; }
        public Nullable<byte> chest_tender_chest_wall { get; set; }
        public Nullable<byte> chest_position_windpipe_neck { get; set; }
        public Nullable<byte> chest_movement_breathing { get; set; }
        public Nullable<byte> chest_breathing_sound { get; set; }
        public Nullable<byte> chest_air_can_hear { get; set; }
        public Nullable<byte> abdo_size { get; set; }
        public Nullable<byte> abdo_pain_coughing { get; set; }
        public Nullable<byte> abdo_pain_moving { get; set; }
        public Nullable<byte> abdo_pain_puffing { get; set; }
        public Nullable<byte> abdo_area_tenderness_found { get; set; }
        public Nullable<byte> abdo_lumps_swelling_found { get; set; }
        public Nullable<byte> abdo_bowel_sound { get; set; }
        public Nullable<byte> ge_gland_neck_found { get; set; }
        public Nullable<byte> ge_gland_neck_r { get; set; }
        public Nullable<byte> ge_gland_neck_l { get; set; }
        public Nullable<byte> ge_gland_armpit_found { get; set; }
        public Nullable<byte> ge_gland_armpit_r { get; set; }
        public Nullable<byte> ge_gland_armpit_l { get; set; }
        public Nullable<byte> ge_gland_groin_found { get; set; }
        public Nullable<byte> ge_gland_groin_r { get; set; }
        public Nullable<byte> ge_gland_groin_l { get; set; }
        public Nullable<byte> ge_ears { get; set; }
        public Nullable<byte> ge_ears_r { get; set; }
        public Nullable<byte> ge_ears_l { get; set; }
        public Nullable<byte> ge_colour { get; set; }
        public Nullable<byte> ge_eardrum_normal { get; set; }
        public Nullable<byte> ge_eardrum_normal_r { get; set; }
        public Nullable<byte> ge_eardrum_normal_l { get; set; }
        public Nullable<byte> ge_eardrum_wax { get; set; }
        public Nullable<byte> ge_eardrum_wax_r { get; set; }
        public Nullable<byte> ge_eardrum_wax_l { get; set; }
        public Nullable<byte> ge_eardrum_red { get; set; }
        public Nullable<byte> ge_eardrum_red_r { get; set; }
        public Nullable<byte> ge_eardrum_red_l { get; set; }
        public Nullable<byte> ge_eardrum_perforated { get; set; }
        public Nullable<byte> ge_eardrum_perforated_r { get; set; }
        public Nullable<byte> ge_eardrum_perforated_l { get; set; }
        public Nullable<byte> ge_throat_colour { get; set; }
        public Nullable<byte> ge_tonsil_size { get; set; }
        public Nullable<byte> ge_skin_rush { get; set; }
        public Nullable<double> ge_skin_rush_size { get; set; }
        public string ge_skin_rush_colour { get; set; }
        public string ge_skin_rush_surface { get; set; }
        public string inves_peak { get; set; }
        public Nullable<byte> urine_testing_blood { get; set; }
        public Nullable<byte> urine_testing_glucose { get; set; }
        public Nullable<byte> urine_testing_ph { get; set; }
        public Nullable<byte> urine_testing_protein { get; set; }
        public Nullable<byte> urine_testing_sg { get; set; }
        public string urine_testing_other { get; set; }
        public string comment_finding { get; set; }
        public Nullable<byte> comment_finding_no { get; set; }
        public string possible_diagnosis { get; set; }
        public string diag_name { get; set; }
        public Nullable<byte> post_designation { get; set; }
        public string treatment_date { get; set; }
        public string patient_name { get; set; }
    }
    
}
