//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class unit_paf
    {
        public unit_paf()
        {
            tanggal = DateTime.Now;
            calculated_paf = 100;
            measured_paf = 100;
        }

        public int id { get; set; }
        public Nullable<int> id_unit { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<double> measured_paf { get; set; }
        public Nullable<double> calculated_paf { get; set; }

        public virtual unit unit { get; set; }
    }
    
}
