//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarEnergi.WWService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModel", Namespace="http://schemas.datacontract.org/2004/07/StarEnergyService.Helper")]
    [System.SerializableAttribute()]
    public partial class ResponseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StarEnergi.WWService.UserModel resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StarEnergi.WWService.ListUserModel resultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StarEnergi.WWService.UserModel result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StarEnergi.WWService.ListUserModel results {
            get {
                return this.resultsField;
            }
            set {
                if ((object.ReferenceEquals(this.resultsField, value) != true)) {
                    this.resultsField = value;
                    this.RaisePropertyChanged("results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/StarEnergyService")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alpha_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> approval_levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> delagateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> dept_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> employee_bossField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> employee_delegateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> employee_deptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employee_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alpha_name {
            get {
                return this.alpha_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.alpha_nameField, value) != true)) {
                    this.alpha_nameField = value;
                    this.RaisePropertyChanged("alpha_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> approval_level {
            get {
                return this.approval_levelField;
            }
            set {
                if ((this.approval_levelField.Equals(value) != true)) {
                    this.approval_levelField = value;
                    this.RaisePropertyChanged("approval_level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> delagate {
            get {
                return this.delagateField;
            }
            set {
                if ((this.delagateField.Equals(value) != true)) {
                    this.delagateField = value;
                    this.RaisePropertyChanged("delagate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> dept_id {
            get {
                return this.dept_idField;
            }
            set {
                if ((this.dept_idField.Equals(value) != true)) {
                    this.dept_idField = value;
                    this.RaisePropertyChanged("dept_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> employee_boss {
            get {
                return this.employee_bossField;
            }
            set {
                if ((this.employee_bossField.Equals(value) != true)) {
                    this.employee_bossField = value;
                    this.RaisePropertyChanged("employee_boss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> employee_delegate {
            get {
                return this.employee_delegateField;
            }
            set {
                if ((this.employee_delegateField.Equals(value) != true)) {
                    this.employee_delegateField = value;
                    this.RaisePropertyChanged("employee_delegate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> employee_dept {
            get {
                return this.employee_deptField;
            }
            set {
                if ((this.employee_deptField.Equals(value) != true)) {
                    this.employee_deptField = value;
                    this.RaisePropertyChanged("employee_dept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employee_no {
            get {
                return this.employee_noField;
            }
            set {
                if ((object.ReferenceEquals(this.employee_noField, value) != true)) {
                    this.employee_noField = value;
                    this.RaisePropertyChanged("employee_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListUserModel", Namespace="http://schemas.datacontract.org/2004/07/StarEnergyService.Helper")]
    [System.SerializableAttribute()]
    public partial class ListUserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StarEnergi.WWService.UserModel[] listUserModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StarEnergi.WWService.UserModel[] listUserModel {
            get {
                return this.listUserModelField;
            }
            set {
                if ((object.ReferenceEquals(this.listUserModelField, value) != true)) {
                    this.listUserModelField = value;
                    this.RaisePropertyChanged("listUserModel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WWService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/listUser", ReplyAction="http://tempuri.org/IUserService/listUserResponse")]
        StarEnergi.WWService.ResponseModel listUser(string token, System.Nullable<int> id, int count, int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getUser", ReplyAction="http://tempuri.org/IUserService/getUserResponse")]
        StarEnergi.WWService.ResponseModel getUser(string token, System.Nullable<int> idLogin, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getSubordinat", ReplyAction="http://tempuri.org/IUserService/getSubordinatResponse")]
        StarEnergi.WWService.ResponseModel getSubordinat(string token, int idLogin, int idUser, bool withSuperintendent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/sendEmail", ReplyAction="http://tempuri.org/IUserService/sendEmailResponse")]
        StarEnergi.WWService.ResponseModel sendEmail(string token, int idLogin, string[] email, string content, string subject, string filename, byte[] attachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/resendEmail", ReplyAction="http://tempuri.org/IUserService/resendEmailResponse")]
        string resendEmail(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getSuperintendent", ReplyAction="http://tempuri.org/IUserService/getSuperintendentResponse")]
        StarEnergi.WWService.ResponseModel getSuperintendent(string token, int idLogin, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getListAdminSHE", ReplyAction="http://tempuri.org/IUserService/getListAdminSHEResponse")]
        StarEnergi.WWService.ResponseModel getListAdminSHE(string token, int idLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/login", ReplyAction="http://tempuri.org/IUserService/loginResponse")]
        StarEnergi.WWService.ResponseModel login(string username, string encodedPassword, System.Nullable<int> role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getSuperintendentByDepartment", ReplyAction="http://tempuri.org/IUserService/getSuperintendentByDepartmentResponse")]
        StarEnergi.WWService.ResponseModel getSuperintendentByDepartment(string token, int idLogin, string department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getSupervisor", ReplyAction="http://tempuri.org/IUserService/getSupervisorResponse")]
        StarEnergi.WWService.ResponseModel getSupervisor(string token, int idLogin, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getAllDepartments", ReplyAction="http://tempuri.org/IUserService/getAllDepartmentsResponse")]
        StarEnergi.WWService.ResponseModel getAllDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        StarEnergi.WWService.ResponseModel CreateUser(string passKey, string name, string companyName, string email, string position, System.DateTime dob, string badgeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveUser", ReplyAction="http://tempuri.org/IUserService/RemoveUserResponse")]
        StarEnergi.WWService.ResponseModel RemoveUser(string passKey, string name, string companyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SetScheduleTraining", ReplyAction="http://tempuri.org/IUserService/SetScheduleTrainingResponse")]
        StarEnergi.WWService.ResponseModel SetScheduleTraining(string[] nameList, string company, string room, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateNotification", ReplyAction="http://tempuri.org/IUserService/CreateNotificationResponse")]
        StarEnergi.WWService.ResponseModel CreateNotification(string passKey, int idLogin, string applicationName, string reportName, string remarks, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateNotificationList", ReplyAction="http://tempuri.org/IUserService/CreateNotificationListResponse")]
        StarEnergi.WWService.ResponseModel CreateNotificationList(string passKey, int[] listIdLogin, string applicationName, string reportName, string remarks, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/NotifactionIsSeen", ReplyAction="http://tempuri.org/IUserService/NotifactionIsSeenResponse")]
        StarEnergi.WWService.ResponseModel NotifactionIsSeen(string passKey, int id, int idLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserNotification", ReplyAction="http://tempuri.org/IUserService/GetUserNotificationResponse")]
        string GetUserNotification(string request, int userId, string passKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : global::StarEnergi.WWService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<global::StarEnergi.WWService.IUserService>, global::StarEnergi.WWService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StarEnergi.WWService.ResponseModel listUser(string token, System.Nullable<int> id, int count, int offset) {
            return base.Channel.listUser(token, id, count, offset);
        }
        
        public StarEnergi.WWService.ResponseModel getUser(string token, System.Nullable<int> idLogin, int idUser) {
            return base.Channel.getUser(token, idLogin, idUser);
        }
        
        public StarEnergi.WWService.ResponseModel getSubordinat(string token, int idLogin, int idUser, bool withSuperintendent) {
            return base.Channel.getSubordinat(token, idLogin, idUser, withSuperintendent);
        }
        
        public StarEnergi.WWService.ResponseModel sendEmail(string token, int idLogin, string[] email, string content, string subject, string filename, byte[] attachment) {
            return base.Channel.sendEmail(token, idLogin, email, content, subject, filename, attachment);
        }
        
        public string resendEmail(string token) {
            return base.Channel.resendEmail(token);
        }
        
        public StarEnergi.WWService.ResponseModel getSuperintendent(string token, int idLogin, int idUser) {
            return base.Channel.getSuperintendent(token, idLogin, idUser);
        }
        
        public StarEnergi.WWService.ResponseModel getListAdminSHE(string token, int idLogin) {
            return base.Channel.getListAdminSHE(token, idLogin);
        }
        
        public StarEnergi.WWService.ResponseModel login(string username, string encodedPassword, System.Nullable<int> role) {
            return base.Channel.login(username, encodedPassword, role);
        }
        
        public StarEnergi.WWService.ResponseModel getSuperintendentByDepartment(string token, int idLogin, string department) {
            return base.Channel.getSuperintendentByDepartment(token, idLogin, department);
        }
        
        public StarEnergi.WWService.ResponseModel getSupervisor(string token, int idLogin, int idUser) {
            return base.Channel.getSupervisor(token, idLogin, idUser);
        }
        
        public StarEnergi.WWService.ResponseModel getAllDepartments() {
            return base.Channel.getAllDepartments();
        }
        
        public StarEnergi.WWService.ResponseModel CreateUser(string passKey, string name, string companyName, string email, string position, System.DateTime dob, string badgeNo) {
            return base.Channel.CreateUser(passKey, name, companyName, email, position, dob, badgeNo);
        }
        
        public StarEnergi.WWService.ResponseModel RemoveUser(string passKey, string name, string companyName) {
            return base.Channel.RemoveUser(passKey, name, companyName);
        }
        
        public StarEnergi.WWService.ResponseModel SetScheduleTraining(string[] nameList, string company, string room, System.DateTime start, System.DateTime end) {
            return base.Channel.SetScheduleTraining(nameList, company, room, start, end);
        }
        
        public StarEnergi.WWService.ResponseModel CreateNotification(string passKey, int idLogin, string applicationName, string reportName, string remarks, string url) {
            return base.Channel.CreateNotification(passKey, idLogin, applicationName, reportName, remarks, url);
        }
        
        public StarEnergi.WWService.ResponseModel CreateNotificationList(string passKey, int[] listIdLogin, string applicationName, string reportName, string remarks, string url) {
            return base.Channel.CreateNotificationList(passKey, listIdLogin, applicationName, reportName, remarks, url);
        }
        
        public StarEnergi.WWService.ResponseModel NotifactionIsSeen(string passKey, int id, int idLogin) {
            return base.Channel.NotifactionIsSeen(passKey, id, idLogin);
        }
        
        public string GetUserNotification(string request, int userId, string passKey) {
            return base.Channel.GetUserNotification(request, userId, passKey);
        }
    }
}
