//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class afp
    {
        public afp()
        {
            this.equipments = new HashSet<equipment>();
        }
    
        public int id { get; set; }
        public Nullable<double> afp_value { get; set; }
        public string afp_description { get; set; }
        public Nullable<double> afp_score { get; set; }
    
        public virtual ICollection<equipment> equipments { get; set; }
    }
    
}
