//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class bom_equipment
    {
        public int id { get; set; }
        public int id_bom { get; set; }
        public int id_equipment { get; set; }
        public string remark { get; set; }
        public virtual build_of_material build_of_material { get; set; }
        public virtual equipment equipment { get; set; }
    }
    
}
