//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class build_of_material
    {
        public build_of_material()
        {
            this.bom_component = new HashSet<bom_component>();
            this.bom_equipment = new HashSet<bom_equipment>();
        }
    
        public int id { get; set; }
        [Required]
        [DisplayName("Functional Location")]
        public string functional_location { get; set; }
        [Required]
        [DisplayName("No Key Map")]
        public string no_keymap { get; set; }
        public bool is_delete { get; set; }
    
        public virtual ICollection<bom_component> bom_component { get; set; }
        public virtual ICollection<bom_equipment> bom_equipment { get; set; }
    }
    
}
