//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class component
    {
        public component()
        {
            this.sub_component = new HashSet<sub_component>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_equipment_part { get; set; }

        [Display(Name = "No Key Map")]
        public string tag_number { get; set; }
        public string description { get; set; }

        [Display(Name = "Component Name")]
        public string component_name { get; set; }

        [Display(Name = "Func Code")]
        public string functional_code { get; set; }

        [Display(Name = "Installed Date")]
        public Nullable<DateTime> installed_date { get; set; }

        public virtual equipment_part equipment_part { get; set; }
        public virtual ICollection<sub_component> sub_component { get; set; }
        public virtual ICollection<bom_component> bom_component { get; set; }
    }
    
}
