//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class daily_log_wells
    {
        public daily_log_wells()
        {
            this.daily_log = new HashSet<daily_log>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual ICollection<daily_log> daily_log { get; set; }
    }
    
}
