//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class daily_log_wells
    {
        public int id { get; set; }

        [Required]
        [MaxLength(255)]
        public string name { get; set; }
        public Nullable<bool> is_delete { get; set; }
    }
    
}
