//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class daily_log_to_wells
    {
        public int daily_log_id { get; set; }
        public int daily_log_wells_id { get; set; }
        public string fcv { get; set; }
        public string flow { get; set; }
        public string whp { get; set; }
        public Nullable<byte> is_text { get; set; }
    
        public virtual daily_log daily_log { get; set; }
        public virtual daily_log_wells daily_log_wells { get; set; }
    }
    
}
