//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class daily_log
    {
        public daily_log()
        {
            this.daily_log_last_plant_status = new HashSet<daily_log_last_plant_status>();
            this.daily_log_maintainence = new HashSet<daily_log_maintainence>();
            this.daily_log_power_stations = new HashSet<daily_log_power_stations>();
            this.daily_log_pro = new HashSet<daily_log_pro>();
            this.daily_log_sags = new HashSet<daily_log_sags>();
            this.daily_log_sap = new HashSet<daily_log_sap>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string grup { get; set; }
        public string production_foreman { get; set; }
        public string production_operator_1 { get; set; }
        public string production_operator_2 { get; set; }
        public string production_operator_3 { get; set; }
        public string production_operator_4 { get; set; }
        public string production_operator_5 { get; set; }
        public string production_operator_6 { get; set; }
        public string production_operator_7 { get; set; }
        public string production_operator_8 { get; set; }
        public Nullable<System.TimeSpan> time_check { get; set; }
        public Nullable<byte> wma_2_is_text { get; set; }
        public string wma_2_fcv { get; set; }
        public string wma_2_flow { get; set; }
        public string wma_2_whp { get; set; }
        public Nullable<byte> wma_4_is_text { get; set; }
        public string wma_4_fcv { get; set; }
        public string wma_4_flow { get; set; }
        public string wma_4_whp { get; set; }
        public Nullable<byte> wma_6_is_text { get; set; }
        public string wma_6_fcv { get; set; }
        public string wma_6_flow { get; set; }
        public string wma_6_whp { get; set; }
        public Nullable<byte> mbd_1_is_text { get; set; }
        public string mbd_1_fcv { get; set; }
        public string mbd_1_flow { get; set; }
        public string mbd_1_whp { get; set; }
        public Nullable<byte> mbd_2_is_text { get; set; }
        public string mbd_2_fcv { get; set; }
        public string mbd_2_flow { get; set; }
        public string mbd_2_whp { get; set; }
        public Nullable<byte> mbd_3_is_text { get; set; }
        public string mbd_3_fcv { get; set; }
        public string mbd_3_flow { get; set; }
        public string mbd_3_whp { get; set; }
        public Nullable<byte> mbd_4_is_text { get; set; }
        public string mbd_4_fcv { get; set; }
        public string mbd_4_flow { get; set; }
        public string mbd_4_whp { get; set; }
        public Nullable<byte> mbd_5_is_text { get; set; }
        public string mbd_5_fcv { get; set; }
        public string mbd_5_flow { get; set; }
        public string mbd_5_whp { get; set; }
        public Nullable<byte> wwq_1_is_text { get; set; }
        public string wwq_1_fcv { get; set; }
        public string wwq_1_flow { get; set; }
        public string wwq_1_whp { get; set; }
        public Nullable<byte> wwq_2_is_text { get; set; }
        public string wwq_2_fcv { get; set; }
        public string wwq_2_flow { get; set; }
        public string wwq_2_whp { get; set; }
        public Nullable<byte> wwq_3_is_text { get; set; }
        public string wwq_3_fcv { get; set; }
        public string wwq_3_flow { get; set; }
        public string wwq_3_whp { get; set; }
        public Nullable<byte> wwq_4_is_text { get; set; }
        public string wwq_4_fcv { get; set; }
        public string wwq_4_flow { get; set; }
        public string wwq_4_whp { get; set; }
        public Nullable<byte> wwq_5_is_text { get; set; }
        public string wwq_5_fcv { get; set; }
        public string wwq_5_flow { get; set; }
        public string wwq_5_whp { get; set; }
        public Nullable<byte> mbe_3_is_text { get; set; }
        public string mbe_3_fcv { get; set; }
        public string mbe_3_flow { get; set; }
        public string mbe_3_whp { get; set; }
        public Nullable<byte> mbe_4_is_text { get; set; }
        public string mbe_4_fcv { get; set; }
        public string mbe_4_flow { get; set; }
        public string mbe_4_whp { get; set; }
        public Nullable<byte> mba_1_is_text { get; set; }
        public string mba_1_fcv { get; set; }
        public string mba_1_flow { get; set; }
        public string mba_1_whp { get; set; }
        public Nullable<byte> mba_2_is_text { get; set; }
        public string mba_2_fcv { get; set; }
        public string mba_2_flow { get; set; }
        public string mba_2_whp { get; set; }
        public Nullable<byte> mba_3_is_text { get; set; }
        public string mba_3_fcv { get; set; }
        public string mba_3_flow { get; set; }
        public string mba_3_whp { get; set; }
        public Nullable<byte> mba_4_is_text { get; set; }
        public string mba_4_fcv { get; set; }
        public string mba_4_flow { get; set; }
        public string mba_4_whp { get; set; }
        public Nullable<byte> mba_5_is_text { get; set; }
        public string mba_5_fcv { get; set; }
        public string mba_5_flow { get; set; }
        public string mba_5_whp { get; set; }
        public Nullable<byte> mbb_1_is_text { get; set; }
        public string mbb_1_fcv { get; set; }
        public string mbb_1_flow { get; set; }
        public string mbb_1_whp { get; set; }
        public Nullable<byte> mbb_2_is_text { get; set; }
        public string mbb_2_fcv { get; set; }
        public string mbb_2_flow { get; set; }
        public string mbb_2_whp { get; set; }
        public Nullable<byte> mbb_3_is_text { get; set; }
        public string mbb_3_fcv { get; set; }
        public string mbb_3_flow { get; set; }
        public string mbb_3_whp { get; set; }
        public Nullable<byte> mbb_4_is_text { get; set; }
        public string mbb_4_fcv { get; set; }
        public string mbb_4_flow { get; set; }
        public string mbb_4_whp { get; set; }
        public Nullable<byte> mbb_5_is_text { get; set; }
        public string mbb_5_fcv { get; set; }
        public string mbb_5_flow { get; set; }
        public string mbb_5_whp { get; set; }
        public Nullable<byte> mbb_6_is_text { get; set; }
        public string mbb_6_fcv { get; set; }
        public string mbb_6_flow { get; set; }
        public string mbb_6_whp { get; set; }
        public Nullable<byte> wwf_1_is_text { get; set; }
        public string wwf_1_fcv { get; set; }
        public string wwf_1_flow { get; set; }
        public string wwf_1_whp { get; set; }
        public Nullable<byte> wwf_3_is_text { get; set; }
        public string wwf_3_fcv { get; set; }
        public string wwf_3_flow { get; set; }
        public string wwf_3_whp { get; set; }
        public Nullable<byte> www_1_is_text { get; set; }
        public string www_1_fcv { get; set; }
        public string www_1_flow { get; set; }
        public string www_1_whp { get; set; }
        public Nullable<byte> wwp_1_is_text { get; set; }
        public string wwp_1_fcv { get; set; }
        public string wwp_1_flow { get; set; }
        public string wwp_1_whp { get; set; }
        public string generator_output_1 { get; set; }
        public string gross_1 { get; set; }
        public string generator_output_counter_1 { get; set; }
        public string power_factor_1 { get; set; }
        public string tap_charger_1 { get; set; }
        public string pln_grid_voltage_1 { get; set; }
        public string valve_limiter_1 { get; set; }
        public string governor_output_1 { get; set; }
        public string wcp_counter_1 { get; set; }
        public string condenser_pressure_1 { get; set; }
        public string main_cw_flow_1 { get; set; }
        public string ppc_g_co_1 { get; set; }
        public string interface_pressure_1 { get; set; }
        public string vent_bias_1 { get; set; }
        public string main_cw_pressure_1 { get; set; }
        public string ct_basin_ph_1 { get; set; }
        public string condenser_cw_inlet_a_1 { get; set; }
        public string condenser_cw_inlet_b_1 { get; set; }
        public string gen_trans_winding_temp_1 { get; set; }
        public string unit_trans_winding_temp_1 { get; set; }
        public string wheel_case_pressure_1 { get; set; }
        public string generator_output_2 { get; set; }
        public string gross_2 { get; set; }
        public string generator_output_counter_2 { get; set; }
        public string power_factor_2 { get; set; }
        public string tap_charger_2 { get; set; }
        public string pln_grid_voltage_2 { get; set; }
        public string valve_limiter_2 { get; set; }
        public string governor_output_2 { get; set; }
        public string wcp_counter_2 { get; set; }
        public string condenser_pressure_2 { get; set; }
        public string main_cw_flow_2 { get; set; }
        public string ppc_g_co_2 { get; set; }
        public string interface_pressure_2 { get; set; }
        public string vent_bias_2 { get; set; }
        public string main_cw_pressure_2 { get; set; }
        public string ct_basin_ph_2 { get; set; }
        public string condenser_cw_inlet_a_2 { get; set; }
        public string condenser_cw_inlet_b_2 { get; set; }
        public string gen_trans_winding_temp_2 { get; set; }
        public string unit_trans_winding_temp_2 { get; set; }
        public string wheel_case_pressure_2 { get; set; }
        public string ncg_1 { get; set; }
        public string ncg_2 { get; set; }
        public string turbine_1 { get; set; }
        public string turbine_2 { get; set; }
        public string ct_temp_1 { get; set; }
        public string ct_temp_2 { get; set; }
        public string exhaust_1 { get; set; }
        public string exhaust_2 { get; set; }
        public string upper_tp_level { get; set; }
        public string lower_tp_level { get; set; }
        public string mv_333 { get; set; }
        public string mv_334 { get; set; }
        public string brine_level { get; set; }
        public string condensate_level { get; set; }
        public string naoh_level { get; set; }
        public string wwd_pond_level { get; set; }
        public string uti_active_1 { get; set; }
        public string uti_reactive_1 { get; set; }
        public string sc_main_1 { get; set; }
        public string sc_auxiliary_1 { get; set; }
        public string ge_active_1 { get; set; }
        public string ge_reactive_1 { get; set; }
        public string metering_segwwl_1 { get; set; }
        public string metering_pln_1 { get; set; }
        public string condensate_ps_1 { get; set; }
        public string segwwl_availability_1 { get; set; }
        public string pln_dispatch_1 { get; set; }
        public string pln_meter_1 { get; set; }
        public string segwwl_export_1 { get; set; }
        public string actual_export_1 { get; set; }
        public string production_excess_1 { get; set; }
        public string rpf_1 { get; set; }
        public string pgf_1 { get; set; }
        public string pln_1 { get; set; }
        public string uti_active_2 { get; set; }
        public string uti_reactive_2 { get; set; }
        public string sc_main_2 { get; set; }
        public string sc_auxiliary_2 { get; set; }
        public string ge_active_2 { get; set; }
        public string ge_reactive_2 { get; set; }
        public string metering_segwwl_2 { get; set; }
        public string metering_pln_2 { get; set; }
        public string condensate_ps_2 { get; set; }
        public string segwwl_availability_2 { get; set; }
        public string pln_dispatch_2 { get; set; }
        public string pln_meter_2 { get; set; }
        public string segwwl_export_2 { get; set; }
        public string actual_export_2 { get; set; }
        public string production_excess_2 { get; set; }
        public string rpf_2 { get; set; }
        public string pgf_2 { get; set; }
        public string pln_2 { get; set; }
        public string condensate_total { get; set; }
        public string brine_total { get; set; }
        public string note { get; set; }
        public string last_plant_time { get; set; }
        public string user_shift { get; set; }
        public Nullable<byte> shift { get; set; }
        public Nullable<byte> is_approve { get; set; }
        public Nullable<int> id_shift2 { get; set; }
        public string achievement_1 { get; set; }
        public string achievement_2 { get; set; }
        public string remark_1 { get; set; }
        public string remark_2 { get; set; }
    
        public virtual ICollection<daily_log_last_plant_status> daily_log_last_plant_status { get; set; }
        public virtual ICollection<daily_log_maintainence> daily_log_maintainence { get; set; }
        public virtual ICollection<daily_log_power_stations> daily_log_power_stations { get; set; }
        public virtual ICollection<daily_log_pro> daily_log_pro { get; set; }
        public virtual ICollection<daily_log_sags> daily_log_sags { get; set; }
        public virtual ICollection<daily_log_sap> daily_log_sap { get; set; }
    
        public virtual List<daily_log_last_plant_status> list_daily_log_last_plant_status { get; set; }
        public virtual List<daily_log_maintainence> list_daily_log_maintainence { get; set; }
        public virtual List<daily_log_power_stations> list_daily_log_power_stations { get; set; }
        public virtual List<daily_log_pro> list_daily_log_pro { get; set; }
        public virtual List<daily_log_sags> list_daily_log_sags { get; set; }
        public virtual List<daily_log_sap> list_daily_log_sap { get; set; }
        public virtual List<daily_log_operation_warning> list_daily_log_operation_warning { get; set; }

        public virtual daily_log daily_log_shift2 { get; set; }

        public virtual string target_sh1 { get; set; }
        public virtual string target_sh2 { get; set; }
        public virtual List<string> attach { get; set; }
    }
    
}
