//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class email_error
    {
        public int id { get; set; }
        public string emails { get; set; }
        public string content { get; set; }
        public string subject { get; set; }
        public string exception { get; set; }
    }
    
}
