//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class employee
    {
        public employee()
        {
            this.employee1 = new HashSet<employee>();
            this.rca_implementation = new HashSet<rca_implementation>();
            this.users = new HashSet<user>();
        }
    
        [Key]
        public int id { get; set; }

        [Required]
        [Display(Name = "Employee No.")]
        public string employee_no { get; set; }

        [Required]
        [Display(Name = "Alpha Name")]
        public string alpha_name { get; set; }

        [Required]
        [Display(Name = "Position")]
        public string position { get; set; }

        [Required]
        [Display(Name = "Work Location")]
        public string work_location { get; set; }

        public Nullable<int> employee_dept { get; set; }

        [Required]
        [Display(Name = "DOH")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> employee_boss { get; set; }
        public Nullable<int> dept_id { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string email { get; set; }
        public string signature { get; set; }

        public Nullable<byte> delagate { get; set; }
        public Nullable<int> employee_delegate { get; set; }

        [Display(Name = "Department")]
        public string department { get; set; }
    
        public virtual ICollection<employee> employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual employee_dept employee_dept1 { get; set; }
        public virtual ICollection<rca_implementation> rca_implementation { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
    
}
