//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class equipment_paf
    {
        public equipment_paf()
        {
            tanggal = DateTime.Now;
            avail_calculated = 100;
            avail_measured = 100;
        }

        public int id { get; set; }
        public int id_equipment { get; set; }
        public System.DateTime tanggal { get; set; }
        public double avail_calculated { get; set; }
        public double avail_measured { get; set; }

        public virtual equipment equipment { get; set; }
    }
    
}
