//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class equipment_groups
    {
        public equipment_groups()
        {
            this.equipments = new HashSet<equipment>();
        }
    
        public int id { get; set; }
        public int id_system { get; set; }
        public string nama { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<equipment> equipments { get; set; }
        public virtual system system { get; set; }
    }
    
}
