//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class iir_recommendations
    {
        public int id { get; set; }
        public Nullable<int> id_iir { get; set; }
        public string description { get; set; }
        public string PIC { get; set; }
        public Nullable<int> pir_number { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public Nullable<byte> has_pir { get; set; }
        public Nullable<int> id_rca { get; set; }

        public string pir_number_string { get; set; }
    
        public virtual investigation_report investigation_report { internal get; set; }
        public virtual pir pir {internal get; set; }
    }
    
}
