//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class monthly_project_activity
    {
        public int id { get; set; }
        public Nullable<int> id_monthly_project { get; set; }
        public string activity { get; set; }
    }
    
}
