//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class part_unit_event
    {
        public part_unit_event()
        {
            durasi = 0;
            downtime = 0;
            status = 1;
        }

        public int id { get; set; }
        public int id_equipment_part { get; set; }
        public Nullable<System.DateTime> datetime_stop { get; set; }
        public Nullable<System.DateTime> datetime_ops { get; set; }
        public Nullable<double> durasi { get; set; }
        public Nullable<double> downtime { get; set; }
        public string failure_mode { get; set; }
        public string failure_cause { get; set; }
        public string failure_effect { get; set; }
        public string secondary_effect { get; set; }
        public string failure_severity { get; set; }
        public string failure_clss { get; set; }
        public string immediate_act { get; set; }
        public string long_term_act { get; set; }
        public string engineer { get; set; }
        public Nullable<double> financial_cost { get; set; }
        public Nullable<double> repair_cost { get; set; }
        public string event_description { get; set; }
        public string type { get; set; }
        public Nullable<byte> status { get; set; }

        public virtual equipment_part equipment_part { get; set; }
    }
    
}
