//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class pt
    {
        public pt()
        {
            this.systems = new HashSet<system>();
        }
    
        public int id { get; set; }
        public Nullable<double> pt_value { get; set; }
        public string pt_description { get; set; }
        public Nullable<double> pt_score { get; set; }
    
        public virtual ICollection<system> systems { get; set; }
    }
    
}
