//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class rca_section
    {
        public rca_section()
        {
            this.rcas = new HashSet<rca>();
        }
    
        public int id { get; set; }
        public int id_department { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<rca> rcas { internal get; set; }
        public virtual rca_department rca_department { get; set; }
    }
    
}
