//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class rca_preserve_category
    {
        public rca_preserve_category()
        {
            this.rca_pre_task = new HashSet<rca_pre_task>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<rca_pre_task> rca_pre_task { get; set; }
    }
    
}
