//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class rca_pre_task
    {
        public int id { get; set; }
        public Nullable<int> id_rca { get; set; }

        public string task { get; set; }
        public Nullable<int> pic { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> target_date { get; set; }
        public string data_to_collect { get; set; }
        public Nullable<int> id_category { get; set; }
    
        public virtual employee employee { internal get; set; }
        public virtual rca_preserve_category rca_preserve_category { internal get; set; }
    }
    
}
