//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class rca_team_connector
    {
        public int id { get; set; }
        public string id_user { get; set; }
        public int id_rca { get; set; }
        public Nullable<byte> rca_position { get; set; }
    
        public virtual rca rca { get; set; }
    }
    
}
