//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class safe_man_hours
    {
        public int id { get; set; }
        public Nullable<System.DateTime> month { get; set; }
        public Nullable<int> seg_shift { get; set; }
        public Nullable<int> seg_non_shift { get; set; }
        public Nullable<int> seg_work_hr_shift { get; set; }
        public Nullable<int> seg_work_hr_non_shift { get; set; }
        public Nullable<int> seg_total_work_hr_shift { get; set; }
        public Nullable<int> seg_total_work_hr_non_shift { get; set; }
        public Nullable<int> seg_total_work_hr { get; set; }
        public Nullable<int> seg_total { get; set; }
        public Nullable<int> cont_shift { get; set; }
        public Nullable<int> cont_non_shift { get; set; }
        public Nullable<int> cont_work_hr_shift { get; set; }
        public Nullable<int> cont_work_hr_non_shift { get; set; }
        public Nullable<int> cont_total_work_hr_shift { get; set; }
        public Nullable<int> cont_total_work_hr_non_shift { get; set; }
        public Nullable<int> cont_total_work_hr { get; set; }
        public Nullable<int> cont_total { get; set; }
        public Nullable<int> grand_total { get; set; }
        public Nullable<int> work_hr_total { get; set; }
        public Nullable<long> seg_mh_smh { get; set; }
        public Nullable<long> cont_mh_smh { get; set; }
        public Nullable<long> seg_emp_smh { get; set; }
        public Nullable<long> cont_emp_smh { get; set; }
        public Nullable<long> emp_total_smh { get; set; }
        public Nullable<long> mh_total_smh { get; set; }
        public Nullable<long> days_smh { get; set; }
        public Nullable<long> seg_mh_ytd { get; set; }
        public Nullable<long> cont_mh_ytd { get; set; }
        public Nullable<long> seg_emp_ytd { get; set; }
        public Nullable<long> cont_emp_ytd { get; set; }
        public Nullable<long> emp_total_ytd { get; set; }
        public Nullable<long> mh_total_ytd { get; set; }
    }
    
}
