//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class she_observation_undian_winner
    {
        public int id { get; set; }
        public Nullable<int> id_undian { get; set; }
        public Nullable<double> reward { get; set; }
        public Nullable<byte> category { get; set; }
        public Nullable<int> winner_observation { get; set; }
    }
    
}
