//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class she_observation_undian
    {
        public int id { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public Nullable<int> winner_id_she_observation_1 { get; set; }
        public Nullable<int> winner_id_she_observation_2 { get; set; }
        public Nullable<int> winner_id_she_observation_3 { get; set; }

        public string from_period { get; set; }
        public string to_period { get; set; }
        public string winner_name_1 { get; set; }
        public string winner_name_2 { get; set; }
        public string winner_name_3 { get; set; }
    }
    
}
