//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class she_injury_report
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string name { get; set; }
        public string id_number { get; set; }
        public string dept { get; set; }
        public string direct_supervisor { get; set; }
        public string cur_job_exp { get; set; }
        public Nullable<byte> sex { get; set; }
        public string nation { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> bod { get; set; }
        public string job_title { get; set; }
        public Nullable<System.DateTime> doh { get; set; }
        public Nullable<System.TimeSpan> time_start_bef_acc { get; set; }
        public string brief_cause { get; set; }
        public string gc_conscious { get; set; }
        public string gc_blood { get; set; }
        public string gc_respiratory { get; set; }
        public string gc_temperature { get; set; }
        public string gc_pulse_rate { get; set; }
        public string gc_oxygen { get; set; }
        public Nullable<System.TimeSpan> time_survey { get; set; }
        public Nullable<byte> airway { get; set; }
        public Nullable<byte> c_spine { get; set; }
        public Nullable<byte> breathing { get; set; }
        public Nullable<byte> circulation { get; set; }
        public Nullable<byte> hmorhage { get; set; }
        public Nullable<byte> disability { get; set; }
        public Nullable<byte> eye_opening { get; set; }
        public Nullable<byte> verbal_response { get; set; }
        public Nullable<byte> motor_response { get; set; }
        public Nullable<byte> pupils_r { get; set; }
        public Nullable<byte> pupils_l { get; set; }
        public Nullable<byte> pupils_size_r { get; set; }
        public Nullable<byte> pupils_size_l { get; set; }
        public Nullable<byte> trauma_score { get; set; }
        public Nullable<System.TimeSpan> time_trauma { get; set; }
        public Nullable<byte> pm_airway { get; set; }
        public Nullable<byte> pm_c_spine { get; set; }
        public Nullable<byte> pm_breathing { get; set; }
        public string pm_cannula_rt { get; set; }
        public string pm_cannula_lt { get; set; }
        public string pm_iv_fluid { get; set; }
        public string pm_iv_fluid_volume { get; set; }
        public string pm_iv_fluid_time { get; set; }
        public Nullable<byte> pm_h_mans { get; set; }
        public Nullable<byte> pm_h_maccel { get; set; }
        public string analgesia_drugs { get; set; }
        public string splinting { get; set; }
        public string comments { get; set; }
        public string signed { get; set; }
        public string crew { get; set; }
        public string respiratory_rate { get; set; }
        public string oxygen_saturation { get; set; }
        public string blood_pressure { get; set; }
        public string pulse_rate { get; set; }
    }
    
}
