//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class tag_types
    {
        public tag_types()
        {
            this.disciplines = new HashSet<discipline>();
            this.equipments = new HashSet<equipment>();
            this.failure_modes = new HashSet<failure_modes>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<discipline> disciplines { get; set; }
        public virtual ICollection<equipment> equipments { get; set; }
        public virtual ICollection<failure_modes> failure_modes { get; set; }
        public virtual tag_types tag_types1 { get; set; }
        public virtual tag_types tag_types2 { get; set; }
    }
    
}
