//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class unit
    {
        public unit()
        {
            this.systems = new HashSet<system>();
            this.unit_paf = new HashSet<unit_paf>();
        }

        [Key]
        public int id { get; set; }
        public int id_foc { get; set; }

        [Required]
        [Display(Name = "Nama Unit")]
        public string nama { get; set; }

        [Display(Name = "MA")]
        public double ma { get; set; }

        [Display(Name = "MASD")]
        public double masd { get; set; }

        [Display(Name = "Func Code")]
        public string functional_code { get; set; }

        [Display(Name = "Deskripsi")]
        public string unit_description { get; set; }

        public virtual foc foc { get; set; }
        public virtual ICollection<system> systems { get; set; }
        public virtual ICollection<unit_paf> unit_paf { get; set; }
    }
    
}
