//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class user
    {
        public user()
        {
            this.rca_implementation = new HashSet<rca_implementation>();
            this.user_per_role = new HashSet<user_per_role>();
        }
    
        public string username { get; set; }
        public string fullname { get; set; }
        public string password { get; set; }
        public string jabatan { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> rm_role { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual employee employee { internal get; set; }
        public virtual ICollection<rca_implementation> rca_implementation { internal get; set; }
        public virtual ICollection<user_per_role> user_per_role { internal get; set; }
        public virtual ICollection<duty_manager> duty_manager { internal get; set; }
    }
    
}
