//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class bom
    {
        public int id { get; set; }
        public Nullable<int> id_reference { get; set; }
        public Nullable<int> level_equip { get; set; }
        public string no_key_map { get; set; }
        public string description { get; set; }
    }
    
}
