//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class daily_log_weekly_target
    {
        public int id { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> date { get; set; }
        
        [UIHint("Shift")]
        public Nullable<byte> shift { get; set; }

        [DataType(DataType.Text)]
        public string target_unit_1 { get; set; }

        [DataType(DataType.Text)]
        public string target_unit_2 { get; set; }
    }
    
}
