//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class employee_dept
    {
        public employee_dept()
        {
            this.employees = new HashSet<employee>();
        }

        [Key]
        public int id { get; set; }

        [Required]
        [Display(Name = "Nama")]
        public string dept_name { get; set; }
        public Nullable<int> plant_id { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
        public virtual plant plant { get; set; }
    }
    
}
