//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class event_descriptions
    {
        [Key]
        public int id { get; set; }
        [Required]
        public string title { get; set; }
        public string description { get; set; }
    }
    
}
