//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class rca
    {
        public rca()
        {
            this.rca_csf_conector = new HashSet<rca_csf_conector>();
            this.rca_team_connector = new HashSet<rca_team_connector>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> id_type { get; set; }
        public string cost { get; set; }
        public Nullable<int> id_facility { get; set; }
        public Nullable<int> id_division { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<int> id_building { get; set; }
        public Nullable<int> id_floor { get; set; }
        public string functional_location { get; set; }
        public Nullable<int> id_type_equipment { get; set; }
        public Nullable<int> id_equipment_class { get; set; }
        public string other { get; set; }
        public string manufacture { get; set; }
        public Nullable<int> id_csf_connector { get; set; }
        public string charter { get; set; }
        public string comment { get; set; }
        public Nullable<int> id_team { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public Nullable<byte> is_publish { get; set; }
        public string analysis_file { get; set; }
        public string equipment_code { get; set; }
        public Nullable<byte> is_tree { get; set; }
        public Nullable<int> id_pir { get; set; }
        public Nullable<byte> has_pir { get; set; }
        public Nullable<byte> fracas_ir { get; set; }
        public Nullable<int> fracas_ir_id { get; set; }
        public string rca_code { get; set; }
        public Nullable<int> id_iir { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public Nullable<int> id_ir { get; set; }
        public Nullable<System.DateTime> actual_start_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<byte> is_sign { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public string pa_sign { get; set; }
        public string immediate_cause { get; set; }
        public string basic_cause { get; set; }
    
        public virtual pir pir { get; set; }
        public virtual ICollection<rca_csf_conector> rca_csf_conector { get; set; }
        public virtual rca_analisys_type rca_analisys_type { get; set; }
        public virtual rca_building rca_building { get; set; }
        public virtual rca_facility rca_facility { get; set; }
        public virtual rca_floor rca_floor { get; set; }
        public virtual rca_section rca_section { get; set; }
        public virtual ICollection<rca_team_connector> rca_team_connector { get; set; }
    }
    
}
