//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace StarEnergi.Models
{
    public partial class rca_facility
    {
        public rca_facility()
        {
            this.rcas = new HashSet<rca>();
            this.rca_department = new HashSet<rca_department>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<rca> rcas { internal get; set; }
        public virtual ICollection<rca_department> rca_department { internal get; set; }
    }
    
}
