//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class sub_component
    {
        public int id { get; set; }
        public Nullable<int> id_component { get; set; }

        [Display(Name = "No Key Map")]
        public string tag_number { get; set; }
        public string description { get; set; }
    
        public virtual component component { get; set; }
    }
    
}
