//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StarEnergi.Models
{
    public partial class system
    {
        public system()
        {
            this.equipment_groups = new HashSet<equipment_groups>();
            this.system_paf = new HashSet<system_paf>();
        }

        public int id { get; set; }
        public int id_unit { get; set; }

        [Required]
        [Display(Name = "Nama")]
        public string nama { get; set; }

        [Display(Name = "Func Code")]
        public string kode { get; set; }

        [Display(Name = "Func Description")]
        public string funct_description { get; set; }

        [Display(Name = "Failure Scenario")]
        public string failure_scenario { get; set; }

        [Display(Name = "Primary Impact")]
        public string primary_impact { get; set; }

        [Display(Name = "Secondary Impact")]
        public string secondary_impact { get; set; }

        [Display(Name = "Cons Econ")]
        public string cons_econ { get; set; }

        [Display(Name = "Cons HS")]
        public string cons_hs { get; set; }

        [Display(Name = "Cons Env")]
        public string cons_env { get; set; }

        [Display(Name = "Cons Total")]
        public string cons_total { get; set; }

        [Display(Name = "Likelihood")]
        public string likelihood { get; set; }

        [Display(Name = "Crit Code")]
        public string crit_code { get; set; }

        [Display(Name = "Ram Crit")]
        public string ram_crit { get; set; }

        [Display(Name = "Exist Crit")]
        public string exist_crit { get; set; }

        [Display(Name = "H")]
        public string h { get; set; }

        [Display(Name = "E")]
        public string e { get; set; }

        [Display(Name = "Economic")]
        public string econ { get; set; }

        [Display(Name = "Prob")]
        public string prob { get; set; }

        [Display(Name = "Ram Crit 1")]
        public string ram_crit_1 { get; set; }

        [Display(Name = "Ram Crit 2")]
        public string ram_crit_2 { get; set; }

        [Display(Name = "Ram Crit 3")]
        public string ram_crit_3 { get; set; }

        public virtual ICollection<equipment_groups> equipment_groups { get; set; }
        public virtual unit unit { get; set; }
        public virtual ICollection<system_paf> system_paf { get; set; }
    }
    
}
